public class Main {
    public static void main(String[] args) {
        System.out.println("asd");
        int c1 = Integer.parseInt("10101010", 2);;
        System.out.println("c1 = " + c1);
        System.out.println(Integer.toBinaryString(c1));
        System.out.println(Integer.lowestOneBit(c1));
        System.out.println(Integer.highestOneBit(c1));

        System.out.println();
        int c2 = Integer.parseInt("1010101", 2);;
        System.out.println("c2 = " + c2);
        System.out.println(Integer.toBinaryString(c2));
        System.out.println(Integer.lowestOneBit(c2));
        System.out.println(Integer.highestOneBit(c2));

        System.out.println();
        System.out.println(Integer.toBinaryString(c1));
        System.out.println(Integer.toBinaryString(c2));
        System.out.println(Integer.toBinaryString(c1 & c2));
        System.out.println(Integer.toBinaryString(c1 | c2));
        System.out.println(Integer.toBinaryString(c1 ^ c2));
        System.out.println(Integer.toBinaryString(~c1));
        System.out.println(Integer.toBinaryString(~c2));

        System.out.println("int max = " + Integer.toBinaryString(Integer.MAX_VALUE));
        System.out.println("int min = " + Integer.toBinaryString(Integer.MIN_VALUE));

        System.out.println();
        int a1 = 2048;
        System.out.println(Integer.toBinaryString(a1));
        System.out.println("a1 = " + a1);
        a1 >>= 1;
        System.out.println(Integer.toBinaryString(a1));
        System.out.println("a1 = " + a1);
        a1 >>= 1;
        System.out.println(Integer.toBinaryString(a1));
        System.out.println("a1 = " + a1);
        a1 >>= 1;
        System.out.println(Integer.toBinaryString(a1));
        System.out.println("a1 = " + a1);
        a1 >>= 1;
        System.out.println(Integer.toBinaryString(a1));
        System.out.println("a1 = " + a1);
        a1 >>= 1;
        System.out.println(Integer.toBinaryString(a1));
        System.out.println("a1 = " + a1);
        a1 >>= 1;
        System.out.println(Integer.toBinaryString(a1));
        System.out.println("a1 = " + a1);
        a1 >>= 1;
        System.out.println(Integer.toBinaryString(a1));
        System.out.println("a1 = " + a1);
        a1 >>= 1;
        System.out.println(Integer.toBinaryString(a1));
        System.out.println("a1 = " + a1);
        a1 >>= 1;
        System.out.println(Integer.toBinaryString(a1));
        System.out.println("a1 = " + a1);
        a1 >>= 1;
        System.out.println(Integer.toBinaryString(a1));
        System.out.println("a1 = " + a1);
        a1 >>= 1;
        System.out.println(Integer.toBinaryString(a1));
        System.out.println("a1 = " + a1);
        a1 >>= 1;
        System.out.println(Integer.toBinaryString(a1));
        System.out.println("a1 = " + a1);
        a1 >>= 1;
        System.out.println(Integer.toBinaryString(a1));
        System.out.println("a1 = " + a1);
        a1 >>= 1;
        System.out.println(Integer.toBinaryString(a1));
        System.out.println("a1 = " + a1);

        System.out.println();
        System.out.println(charToBinaryString('b'));
        System.out.println(Integer.parseInt(charToBinaryString('b'), 2));

        System.out.println();
        int a2 = Integer.parseInt("11011011000", 2);
        System.out.println("a2 = " + a2);
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        System.out.println("a2 = " + a2);
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        System.out.println("a2 = " + a2);
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        System.out.println("a2 = " + a2);
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        System.out.println("a2 = " + a2);
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        System.out.println("a2 = " + a2);
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        System.out.println("a2 = " + a2);
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        System.out.println("a2 = " + a2);
        a2 <<= 1;
        System.out.println(Integer.toBinaryString(a2));
        System.out.println("a2 = " + a2);

        // ______________
        a2 >>>= 1;
        System.out.println(Integer.toBinaryString(a2));
        System.out.println("a2 = " + a2);
        a2 >>>= 1;
        System.out.println(Integer.toBinaryString(a2));
        System.out.println("a2 = " + a2);
        a2 >>>= 1;
        System.out.println(Integer.toBinaryString(a2));
        System.out.println("a2 = " + a2);
        a2 >>>= 1;
        System.out.println(Integer.toBinaryString(a2));
        System.out.println("a2 = " + a2);
        a2 >>>= 1;
        System.out.println(Integer.toBinaryString(a2));
        System.out.println("a2 = " + a2);
        a2 >>>= 1;
        System.out.println(Integer.toBinaryString(a2));
        System.out.println("a2 = " + a2);
        a2 >>>= 1;
        System.out.println(Integer.toBinaryString(a2));
        System.out.println("a2 = " + a2);
    }

    public static String charToBinaryString(char c) {
        return Integer.toBinaryString(c);
    }
}
